# This workflow will install Python dependencies, execute main.py
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Sentiment Analyser
on:
  workflow_dispatch:
  schedule:
    - cron:  '*/6 * * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Execute py script
      env:
        CLIENT_ID: ${{ secrets.CLIENT_ID }}
        CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
        USER_AGENT: ${{ secrets.USER_AGENT }}
      run: |
        python main.py
    - name: Commit and push if files changed
      run: |
        git diff
        git config --global user.email "SA-bot@github.com"
        git config --global user.name "SA-bot"
        git add -A
        git commit -m "Updated contents" || exit 0
        git push
